### ISSUE TITLE
Cannot ignore `include statements

### ISSUE THREAD

**Issue by sgregk** [dalance/svlint#10]
Is there a way to tell svlint to ignore `include statements? This can be a really useful single-file linter, but it fails if the -i switch isn't provided, and some of my include files are in quite strange paths. Ideally, the tool would simply ignore these, and parse the file without them, treating any unknown functions/modules/interfaces/parameters as 'unknown', verifying the syntax only.

**Comment by dalance** [comment]
Thank you for your proposal.
I added `--ignore-include` option, and released v0.3.1.

**Comment by sgregk** [comment]
Hi dalance,
I've tested this and it works perfectly. 
Thank you!
