### ISSUE TITLE
misspelling "tab_charactor"

### ISSUE THREAD

**Issue by puppuccino** [dalance/svlint#180]
Hi
Just a tiny problem. The sample configuration generated by `svlint --example` has a misspelling -- "tab_charactor".
Supposed to be "tab_character"?
![image](https://user-images.githubusercontent.com/57177806/178412711-809ed6fd-d38e-407c-80bb-25df7d5f423d.png)

**Comment by DaveMcEwan** [comment]
@puppuccino This has already been addressed long ago. The last 3 rules in your screenshot (including "tab_charactor") are aliases for renamed rules, which are kept for backwards compatibility.
See the source here: https://github.com/dalance/svlint/blob/master/build.rs#L14
Would you close the issue please.

**Comment by puppuccino** [comment]
@DaveMcEwan 
I didn't notice that. Thank you!

**Comment by dalance** [comment]
This behaviour may be confusing. So I removed renamed rules from example.
