### ISSUE TITLE
New rule suggestion

### ISSUE THREAD

**Issue by pcsanza** [dalance/svlint#20]
I would like to see a new rule added to enforce including **`default_nettype none** at (near) the top of every module.  This directive forces that every declaration must explicitly define the nettype rather than rely on the implicit rules set up in the language.  The reason this is important is because it is a common mistake to have typographical errors in references to signal names. The default rules in the language will treat the reference to a non existent variable as an implicit declaration of a new variable with the default net type (typically _wire_) and will not yield an immediate compile time error - it can be detected only with careful simulation and testing.  Whereas, including the suggested directive in the module will force an immediate compile time error since the implicit declaration of a new variable (due to typo) will not have a default netttype (i.e., _none_) and cannot be referenced.  Warning: using this lint rule on code that leverages implicit net type _wire_ (e.g. _input x_) will generate a lot of nuisance lint warnings until implicit nettype declarations are converted to explicit nettype declarations (e.g., _input wire x_).

**Comment by dalance** [comment]
Thank you for your suggestion, and sorry for the late reply.
I added `default_nettype_none` rule, and released v0.4.17.
