### ISSUE TITLE
Dev Question: New class of rules, `textrules`, working on lines instead of syntax.

### ISSUE THREAD

**Issue by DaveMcEwan** [dalance/svlint#244]
@dalance I'd like to begin working on the textrules mechanism and as it might
involve lots of moving things around, I'd like to agree on what's sensible
before I begin.

Proposal:
1. What I'm aiming for:
  - Make it clear to users how the tool operates in stages, and give an obvious
    way to configure each stage.
  - Easier for developers/reviewers to navigate the codebase.
  - No broken backward compatibility, and keep the related complexity contained
    in `build.rs`.
2. The new rules operate on text, so call them `textrules`.
  This fits with potential extension with other classes of rules like
  `comprules` and `elabrules`.
3. The existing rules operate on syntax, so rename `rules` -> `syntaxrules`.
  This fits nicely with the naming scheme, but involves a bit of moving.
  - Move `src/rules/` -> `src/syntaxrules/`
  - Move `testcases/(pass|fail)/` -> `testcases/syntaxrules/(pass|fail)/`
  - Move `md/explanation-*.md` -> `md/syntaxrules-explanation-*.md`
  - In the MANUAL, re-title the sections `(Functional|Naming|Style) Rules` ->
    `Syntax (Functional|Naming|Style) Rules`.
  - In `.svlint.toml`, rename the `rules` section to `syntaxrules`, but keep
    backwards compatibility by extending the `RENAMED_RULES` mechanism.
    No changes to the `options` section.
4. If you agree to this scheme, I would put all of the "moving stuff" changes
   on a branch before adding the textrules functionallity (for easier review).

What do you think?

**Comment by dalance** [comment]
I agree all of them.
