### ISSUE TITLE
[feature] Shell completions

### ISSUE THREAD

**Issue by Freed-Wu** [dalance/svlint#245]
Can this program provides completions for common shells? I guess <https://docs.rs/clap_complete/latest/clap_complete/> can be a helper. Same as <https://github.com/dalance/svls>

**Comment by DaveMcEwan** [comment]
Both svlint and svls use clap in the same way to construct the command-line interface.
@Freed-Wu Can you provide some examples of what you'd like to see?

**Comment by Freed-Wu** [comment]
Some examples: <https://github.com/typst/typst/issues/545> <https://github.com/git-lfs/git-lfs/issues/5104>

**Comment by DaveMcEwan** [comment]
Sounds like shell completions could be useful but I'm still not exactly sure what you're after. Perhaps you could open a pull request?

**Comment by Freed-Wu** [comment]
I am not familiar with rust :cry: I just think shell completions is useful so I hope every program I like can support it.

**Comment by Freed-Wu** [comment]
Works for me!
