### ISSUE TITLE
Feature: Plugin lists

### ISSUE THREAD

**Issue by skjdbg** [dalance/svlint#248]
While playing around with multiple plugin rules, I encountered 2 issues which I believe could solved through the same feature:

- The command becomes very long.
- I need one project for each separate plugin.

Allowing a plugin to return multiple rules would solve the issue since I could compile all my rules in one project and have only one argument to give to svlint.
I tried locally (on Windows) to make it so `get_plugin` returns a `Vec<*mut dyn Rule>` instead of a `*mut dyn Rule` and modifying the `load` method from `Linter` to expect that. This solution works great for me, however there might be a better way.

**Comment by DaveMcEwan** [comment]
IMO, it might be ideal timing for this change. This change would break backwards compatibility with existing plugins, and so would the PR #247. If there has to be a break, it would be nice to break just once (in 2 ways) rather than twice.

**Comment by DaveMcEwan** [comment]
@skjdbg Can you point to a branch with your demo code? I guess it would really be one branch on svlint and a matching branch on svlint-plugin-sample.

**Comment by skjdbg** [comment]
Would [https://github.com/skjdbg/svlint-plugin-sample](https://github.com/skjdbg/svlint-plugin-sample) and [https://github.com/skjdbg/svlint](https://github.com/skjdbg/svlint) work ?

I'm not sure if you want me to do a pull request for them or if you want something else.

**Comment by DaveMcEwan** [comment]
Yes, those would be fine but I can only see one branch (master) on each of those. 
I guess the changes are all in 1 commit on each master?
- https://github.com/dalance/svlint/compare/master...skjdbg:svlint:master
- https://github.com/dalance/svlint-plugin-sample/compare/master...skjdbg:svlint-plugin-sample:master

Looks pretty nice to me :)

**Comment by DaveMcEwan** [comment]
In future, it's easier to put changes on a dedicated branch, but these are quite small and only one commit is easy to read.
If you open a pair of pull requests and GitHub will attribute the changes to you (see also #250).
It's worth noting that these changes conflict with #247, so it's up to dalance which goes in first - the second will need to update their changes to match.

**Comment by skjdbg** [comment]
> I guess the changes are all in 1 commit on each master?

Yes, to be honest I have never participated in any open-source project so I don't know how I should do things.

**Comment by skjdbg** [comment]
Closing this issue as the feature was added by merging #255.
