### ISSUE TITLE
Error with math operation in conditional expression

### ISSUE THREAD

**Issue by PingvinOchkolaz** [dalance/svlint#55]
Hi, I get error when use math operation in condition expression. Coul you fix it? (Screen with error is attached)
![cond_error](https://user-images.githubusercontent.com/66461553/105986869-85c83a80-60ae-11eb-8d2a-66d15f565cb1.jpg)

**Comment by dalance** [comment]
Thanks!
I fixed it, and released svlint v0.4.13 and svls v0.1.23.
