### ISSUE TITLE
New Rule Suggestion: Check for non-blocking assignments in always_comb and blocking assignments in always_ff

### ISSUE THREAD

**Issue by AlexLao512** [dalance/svlint#57]
Would love to see a new rule added for not allowing any non-blocking assignments in always_comb and not allowing any blocking assignments in always_ff blocks.

**Comment by dalance** [comment]
Thank you for your suggestion.
I added two rules, and released v0.4.17.

**Comment by AlexLao512** [comment]
Thanks! It works and has already found a bug in our code.
